// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct BeatmapAttributes {
 *     double ar;
 *     double od;
 *     float cs;
 *     float hp;
 *     double clock_rate;
 *     HitWindows hit_windows;
 * }
 * }
 */
public class BeatmapAttributes {

    BeatmapAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_DOUBLE.withName("ar"),
        RosuNative.C_DOUBLE.withName("od"),
        RosuNative.C_FLOAT.withName("cs"),
        RosuNative.C_FLOAT.withName("hp"),
        RosuNative.C_DOUBLE.withName("clock_rate"),
        HitWindows.layout().withName("hit_windows")
    ).withName("BeatmapAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble ar$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static final OfDouble ar$layout() {
        return ar$LAYOUT;
    }

    private static final long ar$OFFSET = $LAYOUT.byteOffset(groupElement("ar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static final long ar$offset() {
        return ar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static double ar(MemorySegment struct) {
        return struct.get(ar$LAYOUT, ar$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static void ar(MemorySegment struct, double fieldValue) {
        struct.set(ar$LAYOUT, ar$OFFSET, fieldValue);
    }

    private static final OfDouble od$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("od"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double od
     * }
     */
    public static final OfDouble od$layout() {
        return od$LAYOUT;
    }

    private static final long od$OFFSET = $LAYOUT.byteOffset(groupElement("od"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double od
     * }
     */
    public static final long od$offset() {
        return od$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double od
     * }
     */
    public static double od(MemorySegment struct) {
        return struct.get(od$LAYOUT, od$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double od
     * }
     */
    public static void od(MemorySegment struct, double fieldValue) {
        struct.set(od$LAYOUT, od$OFFSET, fieldValue);
    }

    private static final OfFloat cs$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("cs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float cs
     * }
     */
    public static final OfFloat cs$layout() {
        return cs$LAYOUT;
    }

    private static final long cs$OFFSET = $LAYOUT.byteOffset(groupElement("cs"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float cs
     * }
     */
    public static final long cs$offset() {
        return cs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float cs
     * }
     */
    public static float cs(MemorySegment struct) {
        return struct.get(cs$LAYOUT, cs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float cs
     * }
     */
    public static void cs(MemorySegment struct, float fieldValue) {
        struct.set(cs$LAYOUT, cs$OFFSET, fieldValue);
    }

    private static final OfFloat hp$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("hp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float hp
     * }
     */
    public static final OfFloat hp$layout() {
        return hp$LAYOUT;
    }

    private static final long hp$OFFSET = $LAYOUT.byteOffset(groupElement("hp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float hp
     * }
     */
    public static final long hp$offset() {
        return hp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hp
     * }
     */
    public static float hp(MemorySegment struct) {
        return struct.get(hp$LAYOUT, hp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hp
     * }
     */
    public static void hp(MemorySegment struct, float fieldValue) {
        struct.set(hp$LAYOUT, hp$OFFSET, fieldValue);
    }

    private static final OfDouble clock_rate$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("clock_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double clock_rate
     * }
     */
    public static final OfDouble clock_rate$layout() {
        return clock_rate$LAYOUT;
    }

    private static final long clock_rate$OFFSET = $LAYOUT.byteOffset(groupElement("clock_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double clock_rate
     * }
     */
    public static final long clock_rate$offset() {
        return clock_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double clock_rate
     * }
     */
    public static double clock_rate(MemorySegment struct) {
        return struct.get(clock_rate$LAYOUT, clock_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double clock_rate
     * }
     */
    public static void clock_rate(MemorySegment struct, double fieldValue) {
        struct.set(clock_rate$LAYOUT, clock_rate$OFFSET, fieldValue);
    }

    private static final GroupLayout hit_windows$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("hit_windows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HitWindows hit_windows
     * }
     */
    public static final GroupLayout hit_windows$layout() {
        return hit_windows$LAYOUT;
    }

    private static final long hit_windows$OFFSET = $LAYOUT.byteOffset(groupElement("hit_windows"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HitWindows hit_windows
     * }
     */
    public static final long hit_windows$offset() {
        return hit_windows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HitWindows hit_windows
     * }
     */
    public static MemorySegment hit_windows(MemorySegment struct) {
        return struct.asSlice(hit_windows$OFFSET, hit_windows$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HitWindows hit_windows
     * }
     */
    public static void hit_windows(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, hit_windows$OFFSET, hit_windows$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

