// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct CatchDifficultyAttributes {
 *     double stars;
 *     double preempt;
 *     uint32_t n_fruits;
 *     uint32_t n_droplets;
 *     uint32_t n_tiny_droplets;
 *     bool is_convert;
 * }
 * }
 */
public class CatchDifficultyAttributes {

    CatchDifficultyAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_DOUBLE.withName("stars"),
        RosuNative.C_DOUBLE.withName("preempt"),
        RosuNative.C_INT.withName("n_fruits"),
        RosuNative.C_INT.withName("n_droplets"),
        RosuNative.C_INT.withName("n_tiny_droplets"),
        RosuNative.C_BOOL.withName("is_convert"),
        MemoryLayout.paddingLayout(3)
    ).withName("CatchDifficultyAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble stars$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final OfDouble stars$layout() {
        return stars$LAYOUT;
    }

    private static final long stars$OFFSET = $LAYOUT.byteOffset(groupElement("stars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final long stars$offset() {
        return stars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static double stars(MemorySegment struct) {
        return struct.get(stars$LAYOUT, stars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static void stars(MemorySegment struct, double fieldValue) {
        struct.set(stars$LAYOUT, stars$OFFSET, fieldValue);
    }

    private static final OfDouble preempt$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("preempt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double preempt
     * }
     */
    public static final OfDouble preempt$layout() {
        return preempt$LAYOUT;
    }

    private static final long preempt$OFFSET = $LAYOUT.byteOffset(groupElement("preempt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double preempt
     * }
     */
    public static final long preempt$offset() {
        return preempt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double preempt
     * }
     */
    public static double preempt(MemorySegment struct) {
        return struct.get(preempt$LAYOUT, preempt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double preempt
     * }
     */
    public static void preempt(MemorySegment struct, double fieldValue) {
        struct.set(preempt$LAYOUT, preempt$OFFSET, fieldValue);
    }

    private static final OfInt n_fruits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_fruits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_fruits
     * }
     */
    public static final OfInt n_fruits$layout() {
        return n_fruits$LAYOUT;
    }

    private static final long n_fruits$OFFSET = $LAYOUT.byteOffset(groupElement("n_fruits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_fruits
     * }
     */
    public static final long n_fruits$offset() {
        return n_fruits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_fruits
     * }
     */
    public static int n_fruits(MemorySegment struct) {
        return struct.get(n_fruits$LAYOUT, n_fruits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_fruits
     * }
     */
    public static void n_fruits(MemorySegment struct, int fieldValue) {
        struct.set(n_fruits$LAYOUT, n_fruits$OFFSET, fieldValue);
    }

    private static final OfInt n_droplets$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_droplets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_droplets
     * }
     */
    public static final OfInt n_droplets$layout() {
        return n_droplets$LAYOUT;
    }

    private static final long n_droplets$OFFSET = $LAYOUT.byteOffset(groupElement("n_droplets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_droplets
     * }
     */
    public static final long n_droplets$offset() {
        return n_droplets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_droplets
     * }
     */
    public static int n_droplets(MemorySegment struct) {
        return struct.get(n_droplets$LAYOUT, n_droplets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_droplets
     * }
     */
    public static void n_droplets(MemorySegment struct, int fieldValue) {
        struct.set(n_droplets$LAYOUT, n_droplets$OFFSET, fieldValue);
    }

    private static final OfInt n_tiny_droplets$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_tiny_droplets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_tiny_droplets
     * }
     */
    public static final OfInt n_tiny_droplets$layout() {
        return n_tiny_droplets$LAYOUT;
    }

    private static final long n_tiny_droplets$OFFSET = $LAYOUT.byteOffset(groupElement("n_tiny_droplets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_tiny_droplets
     * }
     */
    public static final long n_tiny_droplets$offset() {
        return n_tiny_droplets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_tiny_droplets
     * }
     */
    public static int n_tiny_droplets(MemorySegment struct) {
        return struct.get(n_tiny_droplets$LAYOUT, n_tiny_droplets$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_tiny_droplets
     * }
     */
    public static void n_tiny_droplets(MemorySegment struct, int fieldValue) {
        struct.set(n_tiny_droplets$LAYOUT, n_tiny_droplets$OFFSET, fieldValue);
    }

    private static final OfBoolean is_convert$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_convert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final OfBoolean is_convert$layout() {
        return is_convert$LAYOUT;
    }

    private static final long is_convert$OFFSET = $LAYOUT.byteOffset(groupElement("is_convert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final long is_convert$offset() {
        return is_convert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static boolean is_convert(MemorySegment struct) {
        return struct.get(is_convert$LAYOUT, is_convert$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static void is_convert(MemorySegment struct, boolean fieldValue) {
        struct.set(is_convert$LAYOUT, is_convert$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

