// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct HitObjectData {
 *     uint32_t variant;
 *     union {
 *         SliderData slider;
 *         DurationData spinner;
 *         DurationData hold;
 *     } payload;
 * }
 * }
 */
public class HitObjectData {

    HitObjectData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("variant"),
        MemoryLayout.paddingLayout(4),
        HitObjectData.payload.layout().withName("payload")
    ).withName("HitObjectData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt variant$LAYOUT = (OfInt)$LAYOUT.select(groupElement("variant"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final OfInt variant$layout() {
        return variant$LAYOUT;
    }

    private static final long variant$OFFSET = $LAYOUT.byteOffset(groupElement("variant"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final long variant$offset() {
        return variant$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static int variant(MemorySegment struct) {
        return struct.get(variant$LAYOUT, variant$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static void variant(MemorySegment struct, int fieldValue) {
        struct.set(variant$LAYOUT, variant$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     SliderData slider;
     *     DurationData spinner;
     *     DurationData hold;
     * }
     * }
     */
    public static class payload {

        payload() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            SliderData.layout().withName("slider"),
            DurationData.layout().withName("spinner"),
            DurationData.layout().withName("hold")
        ).withName("$anon$182:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final GroupLayout slider$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("slider"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * SliderData slider
         * }
         */
        public static final GroupLayout slider$layout() {
            return slider$LAYOUT;
        }

        private static final long slider$OFFSET = $LAYOUT.byteOffset(groupElement("slider"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * SliderData slider
         * }
         */
        public static final long slider$offset() {
            return slider$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * SliderData slider
         * }
         */
        public static MemorySegment slider(MemorySegment union) {
            return union.asSlice(slider$OFFSET, slider$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * SliderData slider
         * }
         */
        public static void slider(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, slider$OFFSET, slider$LAYOUT.byteSize());
        }

        private static final GroupLayout spinner$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("spinner"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * DurationData spinner
         * }
         */
        public static final GroupLayout spinner$layout() {
            return spinner$LAYOUT;
        }

        private static final long spinner$OFFSET = $LAYOUT.byteOffset(groupElement("spinner"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * DurationData spinner
         * }
         */
        public static final long spinner$offset() {
            return spinner$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * DurationData spinner
         * }
         */
        public static MemorySegment spinner(MemorySegment union) {
            return union.asSlice(spinner$OFFSET, spinner$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * DurationData spinner
         * }
         */
        public static void spinner(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, spinner$OFFSET, spinner$LAYOUT.byteSize());
        }

        private static final GroupLayout hold$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("hold"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * DurationData hold
         * }
         */
        public static final GroupLayout hold$layout() {
            return hold$LAYOUT;
        }

        private static final long hold$OFFSET = $LAYOUT.byteOffset(groupElement("hold"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * DurationData hold
         * }
         */
        public static final long hold$offset() {
            return hold$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * DurationData hold
         * }
         */
        public static MemorySegment hold(MemorySegment union) {
            return union.asSlice(hold$OFFSET, hold$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * DurationData hold
         * }
         */
        public static void hold(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, hold$OFFSET, hold$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout payload$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("payload"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     SliderData slider;
     *     DurationData spinner;
     *     DurationData hold;
     * } payload
     * }
     */
    public static final GroupLayout payload$layout() {
        return payload$LAYOUT;
    }

    private static final long payload$OFFSET = $LAYOUT.byteOffset(groupElement("payload"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     SliderData slider;
     *     DurationData spinner;
     *     DurationData hold;
     * } payload
     * }
     */
    public static final long payload$offset() {
        return payload$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     SliderData slider;
     *     DurationData spinner;
     *     DurationData hold;
     * } payload
     * }
     */
    public static MemorySegment payload(MemorySegment struct) {
        return struct.asSlice(payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     SliderData slider;
     *     DurationData spinner;
     *     DurationData hold;
     * } payload
     * }
     */
    public static void payload(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

