// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct HitWindows {
 *     Option_f64 ar;
 *     Option_f64 od_perfect;
 *     Option_f64 od_great;
 *     Option_f64 od_good;
 *     Option_f64 od_ok;
 *     Option_f64 od_meh;
 * }
 * }
 */
public class HitWindows {

    HitWindows() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Option_f64.layout().withName("ar"),
        Option_f64.layout().withName("od_perfect"),
        Option_f64.layout().withName("od_great"),
        Option_f64.layout().withName("od_good"),
        Option_f64.layout().withName("od_ok"),
        Option_f64.layout().withName("od_meh")
    ).withName("HitWindows");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ar$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 ar
     * }
     */
    public static final GroupLayout ar$layout() {
        return ar$LAYOUT;
    }

    private static final long ar$OFFSET = $LAYOUT.byteOffset(groupElement("ar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 ar
     * }
     */
    public static final long ar$offset() {
        return ar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 ar
     * }
     */
    public static MemorySegment ar(MemorySegment struct) {
        return struct.asSlice(ar$OFFSET, ar$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 ar
     * }
     */
    public static void ar(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ar$OFFSET, ar$LAYOUT.byteSize());
    }

    private static final GroupLayout od_perfect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("od_perfect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 od_perfect
     * }
     */
    public static final GroupLayout od_perfect$layout() {
        return od_perfect$LAYOUT;
    }

    private static final long od_perfect$OFFSET = $LAYOUT.byteOffset(groupElement("od_perfect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 od_perfect
     * }
     */
    public static final long od_perfect$offset() {
        return od_perfect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 od_perfect
     * }
     */
    public static MemorySegment od_perfect(MemorySegment struct) {
        return struct.asSlice(od_perfect$OFFSET, od_perfect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 od_perfect
     * }
     */
    public static void od_perfect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, od_perfect$OFFSET, od_perfect$LAYOUT.byteSize());
    }

    private static final GroupLayout od_great$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("od_great"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 od_great
     * }
     */
    public static final GroupLayout od_great$layout() {
        return od_great$LAYOUT;
    }

    private static final long od_great$OFFSET = $LAYOUT.byteOffset(groupElement("od_great"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 od_great
     * }
     */
    public static final long od_great$offset() {
        return od_great$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 od_great
     * }
     */
    public static MemorySegment od_great(MemorySegment struct) {
        return struct.asSlice(od_great$OFFSET, od_great$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 od_great
     * }
     */
    public static void od_great(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, od_great$OFFSET, od_great$LAYOUT.byteSize());
    }

    private static final GroupLayout od_good$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("od_good"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 od_good
     * }
     */
    public static final GroupLayout od_good$layout() {
        return od_good$LAYOUT;
    }

    private static final long od_good$OFFSET = $LAYOUT.byteOffset(groupElement("od_good"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 od_good
     * }
     */
    public static final long od_good$offset() {
        return od_good$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 od_good
     * }
     */
    public static MemorySegment od_good(MemorySegment struct) {
        return struct.asSlice(od_good$OFFSET, od_good$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 od_good
     * }
     */
    public static void od_good(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, od_good$OFFSET, od_good$LAYOUT.byteSize());
    }

    private static final GroupLayout od_ok$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("od_ok"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 od_ok
     * }
     */
    public static final GroupLayout od_ok$layout() {
        return od_ok$LAYOUT;
    }

    private static final long od_ok$OFFSET = $LAYOUT.byteOffset(groupElement("od_ok"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 od_ok
     * }
     */
    public static final long od_ok$offset() {
        return od_ok$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 od_ok
     * }
     */
    public static MemorySegment od_ok(MemorySegment struct) {
        return struct.asSlice(od_ok$OFFSET, od_ok$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 od_ok
     * }
     */
    public static void od_ok(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, od_ok$OFFSET, od_ok$LAYOUT.byteSize());
    }

    private static final GroupLayout od_meh$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("od_meh"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 od_meh
     * }
     */
    public static final GroupLayout od_meh$layout() {
        return od_meh$LAYOUT;
    }

    private static final long od_meh$OFFSET = $LAYOUT.byteOffset(groupElement("od_meh"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 od_meh
     * }
     */
    public static final long od_meh$offset() {
        return od_meh$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 od_meh
     * }
     */
    public static MemorySegment od_meh(MemorySegment struct) {
        return struct.asSlice(od_meh$OFFSET, od_meh$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 od_meh
     * }
     */
    public static void od_meh(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, od_meh$OFFSET, od_meh$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

