// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ManiaPerformanceAttributes {
 *     ManiaDifficultyAttributes difficulty;
 *     double pp;
 *     double pp_difficulty;
 * }
 * }
 */
public class ManiaPerformanceAttributes {

    ManiaPerformanceAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ManiaDifficultyAttributes.layout().withName("difficulty"),
        RosuNative.C_DOUBLE.withName("pp"),
        RosuNative.C_DOUBLE.withName("pp_difficulty")
    ).withName("ManiaPerformanceAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout difficulty$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("difficulty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ManiaDifficultyAttributes difficulty
     * }
     */
    public static final GroupLayout difficulty$layout() {
        return difficulty$LAYOUT;
    }

    private static final long difficulty$OFFSET = $LAYOUT.byteOffset(groupElement("difficulty"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ManiaDifficultyAttributes difficulty
     * }
     */
    public static final long difficulty$offset() {
        return difficulty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ManiaDifficultyAttributes difficulty
     * }
     */
    public static MemorySegment difficulty(MemorySegment struct) {
        return struct.asSlice(difficulty$OFFSET, difficulty$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ManiaDifficultyAttributes difficulty
     * }
     */
    public static void difficulty(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, difficulty$OFFSET, difficulty$LAYOUT.byteSize());
    }

    private static final OfDouble pp$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static final OfDouble pp$layout() {
        return pp$LAYOUT;
    }

    private static final long pp$OFFSET = $LAYOUT.byteOffset(groupElement("pp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static final long pp$offset() {
        return pp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static double pp(MemorySegment struct) {
        return struct.get(pp$LAYOUT, pp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static void pp(MemorySegment struct, double fieldValue) {
        struct.set(pp$LAYOUT, pp$OFFSET, fieldValue);
    }

    private static final OfDouble pp_difficulty$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_difficulty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_difficulty
     * }
     */
    public static final OfDouble pp_difficulty$layout() {
        return pp_difficulty$LAYOUT;
    }

    private static final long pp_difficulty$OFFSET = $LAYOUT.byteOffset(groupElement("pp_difficulty"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_difficulty
     * }
     */
    public static final long pp_difficulty$offset() {
        return pp_difficulty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_difficulty
     * }
     */
    public static double pp_difficulty(MemorySegment struct) {
        return struct.get(pp_difficulty$LAYOUT, pp_difficulty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_difficulty
     * }
     */
    public static void pp_difficulty(MemorySegment struct, double fieldValue) {
        struct.set(pp_difficulty$LAYOUT, pp_difficulty$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

