// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ManiaDifficultyAttributes {
 *     double stars;
 *     uint32_t n_objects;
 *     uint32_t n_hold_notes;
 *     uint32_t max_combo;
 *     bool is_convert;
 * }
 * }
 */
public class ManiaDifficultyAttributes {

    ManiaDifficultyAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_DOUBLE.withName("stars"),
        RosuNative.C_INT.withName("n_objects"),
        RosuNative.C_INT.withName("n_hold_notes"),
        RosuNative.C_INT.withName("max_combo"),
        RosuNative.C_BOOL.withName("is_convert"),
        MemoryLayout.paddingLayout(3)
    ).withName("ManiaDifficultyAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble stars$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final OfDouble stars$layout() {
        return stars$LAYOUT;
    }

    private static final long stars$OFFSET = $LAYOUT.byteOffset(groupElement("stars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final long stars$offset() {
        return stars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static double stars(MemorySegment struct) {
        return struct.get(stars$LAYOUT, stars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static void stars(MemorySegment struct, double fieldValue) {
        struct.set(stars$LAYOUT, stars$OFFSET, fieldValue);
    }

    private static final OfInt n_objects$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_objects"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_objects
     * }
     */
    public static final OfInt n_objects$layout() {
        return n_objects$LAYOUT;
    }

    private static final long n_objects$OFFSET = $LAYOUT.byteOffset(groupElement("n_objects"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_objects
     * }
     */
    public static final long n_objects$offset() {
        return n_objects$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_objects
     * }
     */
    public static int n_objects(MemorySegment struct) {
        return struct.get(n_objects$LAYOUT, n_objects$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_objects
     * }
     */
    public static void n_objects(MemorySegment struct, int fieldValue) {
        struct.set(n_objects$LAYOUT, n_objects$OFFSET, fieldValue);
    }

    private static final OfInt n_hold_notes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_hold_notes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_hold_notes
     * }
     */
    public static final OfInt n_hold_notes$layout() {
        return n_hold_notes$LAYOUT;
    }

    private static final long n_hold_notes$OFFSET = $LAYOUT.byteOffset(groupElement("n_hold_notes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_hold_notes
     * }
     */
    public static final long n_hold_notes$offset() {
        return n_hold_notes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_hold_notes
     * }
     */
    public static int n_hold_notes(MemorySegment struct) {
        return struct.get(n_hold_notes$LAYOUT, n_hold_notes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_hold_notes
     * }
     */
    public static void n_hold_notes(MemorySegment struct, int fieldValue) {
        struct.set(n_hold_notes$LAYOUT, n_hold_notes$OFFSET, fieldValue);
    }

    private static final OfInt max_combo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_combo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final OfInt max_combo$layout() {
        return max_combo$LAYOUT;
    }

    private static final long max_combo$OFFSET = $LAYOUT.byteOffset(groupElement("max_combo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final long max_combo$offset() {
        return max_combo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static int max_combo(MemorySegment struct) {
        return struct.get(max_combo$LAYOUT, max_combo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static void max_combo(MemorySegment struct, int fieldValue) {
        struct.set(max_combo$LAYOUT, max_combo$OFFSET, fieldValue);
    }

    private static final OfBoolean is_convert$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_convert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final OfBoolean is_convert$layout() {
        return is_convert$LAYOUT;
    }

    private static final long is_convert$OFFSET = $LAYOUT.byteOffset(groupElement("is_convert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final long is_convert$offset() {
        return is_convert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static boolean is_convert(MemorySegment struct) {
        return struct.get(is_convert$LAYOUT, is_convert$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static void is_convert(MemorySegment struct, boolean fieldValue) {
        struct.set(is_convert$LAYOUT, is_convert$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

