// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct Option_u32 {
 *     uint32_t variant;
 *     uint32_t some;
 * }
 * }
 */
public class Option_u32 {

    Option_u32() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("variant"),
        RosuNative.C_INT.withName("some")
    ).withName("Option_u32");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt variant$LAYOUT = (OfInt)$LAYOUT.select(groupElement("variant"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final OfInt variant$layout() {
        return variant$LAYOUT;
    }

    private static final long variant$OFFSET = $LAYOUT.byteOffset(groupElement("variant"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final long variant$offset() {
        return variant$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static int variant(MemorySegment struct) {
        return struct.get(variant$LAYOUT, variant$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static void variant(MemorySegment struct, int fieldValue) {
        struct.set(variant$LAYOUT, variant$OFFSET, fieldValue);
    }

    private static final OfInt some$LAYOUT = (OfInt)$LAYOUT.select(groupElement("some"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t some
     * }
     */
    public static final OfInt some$layout() {
        return some$LAYOUT;
    }

    private static final long some$OFFSET = $LAYOUT.byteOffset(groupElement("some"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t some
     * }
     */
    public static final long some$offset() {
        return some$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t some
     * }
     */
    public static int some(MemorySegment struct) {
        return struct.get(some$LAYOUT, some$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t some
     * }
     */
    public static void some(MemorySegment struct, int fieldValue) {
        struct.set(some$LAYOUT, some$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

