// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OsuDifficultyAttributes {
 *     double aim;
 *     double aim_difficult_slider_count;
 *     double speed;
 *     double flashlight;
 *     double reading;
 *     double slider_factor;
 *     double aim_top_weighted_slider_factor;
 *     double speed_top_weighted_slider_factor;
 *     double speed_note_count;
 *     double aim_difficult_strain_count;
 *     double speed_difficult_strain_count;
 *     double reading_difficult_note_count;
 *     double nested_score_per_object;
 *     double legacy_score_base_multiplier;
 *     double maximum_legacy_combo_score;
 *     double ar;
 *     double great_hit_window;
 *     double ok_hit_window;
 *     double meh_hit_window;
 *     double hp;
 *     uint32_t n_circles;
 *     uint32_t n_sliders;
 *     uint32_t n_large_ticks;
 *     uint32_t n_spinners;
 *     double stars;
 *     uint32_t max_combo;
 * }
 * }
 */
public class OsuDifficultyAttributes {

    OsuDifficultyAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_DOUBLE.withName("aim"),
        RosuNative.C_DOUBLE.withName("aim_difficult_slider_count"),
        RosuNative.C_DOUBLE.withName("speed"),
        RosuNative.C_DOUBLE.withName("flashlight"),
        RosuNative.C_DOUBLE.withName("reading"),
        RosuNative.C_DOUBLE.withName("slider_factor"),
        RosuNative.C_DOUBLE.withName("aim_top_weighted_slider_factor"),
        RosuNative.C_DOUBLE.withName("speed_top_weighted_slider_factor"),
        RosuNative.C_DOUBLE.withName("speed_note_count"),
        RosuNative.C_DOUBLE.withName("aim_difficult_strain_count"),
        RosuNative.C_DOUBLE.withName("speed_difficult_strain_count"),
        RosuNative.C_DOUBLE.withName("reading_difficult_note_count"),
        RosuNative.C_DOUBLE.withName("nested_score_per_object"),
        RosuNative.C_DOUBLE.withName("legacy_score_base_multiplier"),
        RosuNative.C_DOUBLE.withName("maximum_legacy_combo_score"),
        RosuNative.C_DOUBLE.withName("ar"),
        RosuNative.C_DOUBLE.withName("great_hit_window"),
        RosuNative.C_DOUBLE.withName("ok_hit_window"),
        RosuNative.C_DOUBLE.withName("meh_hit_window"),
        RosuNative.C_DOUBLE.withName("hp"),
        RosuNative.C_INT.withName("n_circles"),
        RosuNative.C_INT.withName("n_sliders"),
        RosuNative.C_INT.withName("n_large_ticks"),
        RosuNative.C_INT.withName("n_spinners"),
        RosuNative.C_DOUBLE.withName("stars"),
        RosuNative.C_INT.withName("max_combo"),
        MemoryLayout.paddingLayout(4)
    ).withName("OsuDifficultyAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble aim$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("aim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double aim
     * }
     */
    public static final OfDouble aim$layout() {
        return aim$LAYOUT;
    }

    private static final long aim$OFFSET = $LAYOUT.byteOffset(groupElement("aim"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double aim
     * }
     */
    public static final long aim$offset() {
        return aim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double aim
     * }
     */
    public static double aim(MemorySegment struct) {
        return struct.get(aim$LAYOUT, aim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double aim
     * }
     */
    public static void aim(MemorySegment struct, double fieldValue) {
        struct.set(aim$LAYOUT, aim$OFFSET, fieldValue);
    }

    private static final OfDouble aim_difficult_slider_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("aim_difficult_slider_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double aim_difficult_slider_count
     * }
     */
    public static final OfDouble aim_difficult_slider_count$layout() {
        return aim_difficult_slider_count$LAYOUT;
    }

    private static final long aim_difficult_slider_count$OFFSET = $LAYOUT.byteOffset(groupElement("aim_difficult_slider_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double aim_difficult_slider_count
     * }
     */
    public static final long aim_difficult_slider_count$offset() {
        return aim_difficult_slider_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double aim_difficult_slider_count
     * }
     */
    public static double aim_difficult_slider_count(MemorySegment struct) {
        return struct.get(aim_difficult_slider_count$LAYOUT, aim_difficult_slider_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double aim_difficult_slider_count
     * }
     */
    public static void aim_difficult_slider_count(MemorySegment struct, double fieldValue) {
        struct.set(aim_difficult_slider_count$LAYOUT, aim_difficult_slider_count$OFFSET, fieldValue);
    }

    private static final OfDouble speed$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("speed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double speed
     * }
     */
    public static final OfDouble speed$layout() {
        return speed$LAYOUT;
    }

    private static final long speed$OFFSET = $LAYOUT.byteOffset(groupElement("speed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double speed
     * }
     */
    public static final long speed$offset() {
        return speed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double speed
     * }
     */
    public static double speed(MemorySegment struct) {
        return struct.get(speed$LAYOUT, speed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double speed
     * }
     */
    public static void speed(MemorySegment struct, double fieldValue) {
        struct.set(speed$LAYOUT, speed$OFFSET, fieldValue);
    }

    private static final OfDouble flashlight$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("flashlight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double flashlight
     * }
     */
    public static final OfDouble flashlight$layout() {
        return flashlight$LAYOUT;
    }

    private static final long flashlight$OFFSET = $LAYOUT.byteOffset(groupElement("flashlight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double flashlight
     * }
     */
    public static final long flashlight$offset() {
        return flashlight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double flashlight
     * }
     */
    public static double flashlight(MemorySegment struct) {
        return struct.get(flashlight$LAYOUT, flashlight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double flashlight
     * }
     */
    public static void flashlight(MemorySegment struct, double fieldValue) {
        struct.set(flashlight$LAYOUT, flashlight$OFFSET, fieldValue);
    }

    private static final OfDouble reading$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("reading"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static final OfDouble reading$layout() {
        return reading$LAYOUT;
    }

    private static final long reading$OFFSET = $LAYOUT.byteOffset(groupElement("reading"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static final long reading$offset() {
        return reading$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static double reading(MemorySegment struct) {
        return struct.get(reading$LAYOUT, reading$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static void reading(MemorySegment struct, double fieldValue) {
        struct.set(reading$LAYOUT, reading$OFFSET, fieldValue);
    }

    private static final OfDouble slider_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("slider_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double slider_factor
     * }
     */
    public static final OfDouble slider_factor$layout() {
        return slider_factor$LAYOUT;
    }

    private static final long slider_factor$OFFSET = $LAYOUT.byteOffset(groupElement("slider_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double slider_factor
     * }
     */
    public static final long slider_factor$offset() {
        return slider_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double slider_factor
     * }
     */
    public static double slider_factor(MemorySegment struct) {
        return struct.get(slider_factor$LAYOUT, slider_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double slider_factor
     * }
     */
    public static void slider_factor(MemorySegment struct, double fieldValue) {
        struct.set(slider_factor$LAYOUT, slider_factor$OFFSET, fieldValue);
    }

    private static final OfDouble aim_top_weighted_slider_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("aim_top_weighted_slider_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double aim_top_weighted_slider_factor
     * }
     */
    public static final OfDouble aim_top_weighted_slider_factor$layout() {
        return aim_top_weighted_slider_factor$LAYOUT;
    }

    private static final long aim_top_weighted_slider_factor$OFFSET = $LAYOUT.byteOffset(groupElement("aim_top_weighted_slider_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double aim_top_weighted_slider_factor
     * }
     */
    public static final long aim_top_weighted_slider_factor$offset() {
        return aim_top_weighted_slider_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double aim_top_weighted_slider_factor
     * }
     */
    public static double aim_top_weighted_slider_factor(MemorySegment struct) {
        return struct.get(aim_top_weighted_slider_factor$LAYOUT, aim_top_weighted_slider_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double aim_top_weighted_slider_factor
     * }
     */
    public static void aim_top_weighted_slider_factor(MemorySegment struct, double fieldValue) {
        struct.set(aim_top_weighted_slider_factor$LAYOUT, aim_top_weighted_slider_factor$OFFSET, fieldValue);
    }

    private static final OfDouble speed_top_weighted_slider_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("speed_top_weighted_slider_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double speed_top_weighted_slider_factor
     * }
     */
    public static final OfDouble speed_top_weighted_slider_factor$layout() {
        return speed_top_weighted_slider_factor$LAYOUT;
    }

    private static final long speed_top_weighted_slider_factor$OFFSET = $LAYOUT.byteOffset(groupElement("speed_top_weighted_slider_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double speed_top_weighted_slider_factor
     * }
     */
    public static final long speed_top_weighted_slider_factor$offset() {
        return speed_top_weighted_slider_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double speed_top_weighted_slider_factor
     * }
     */
    public static double speed_top_weighted_slider_factor(MemorySegment struct) {
        return struct.get(speed_top_weighted_slider_factor$LAYOUT, speed_top_weighted_slider_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double speed_top_weighted_slider_factor
     * }
     */
    public static void speed_top_weighted_slider_factor(MemorySegment struct, double fieldValue) {
        struct.set(speed_top_weighted_slider_factor$LAYOUT, speed_top_weighted_slider_factor$OFFSET, fieldValue);
    }

    private static final OfDouble speed_note_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("speed_note_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double speed_note_count
     * }
     */
    public static final OfDouble speed_note_count$layout() {
        return speed_note_count$LAYOUT;
    }

    private static final long speed_note_count$OFFSET = $LAYOUT.byteOffset(groupElement("speed_note_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double speed_note_count
     * }
     */
    public static final long speed_note_count$offset() {
        return speed_note_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double speed_note_count
     * }
     */
    public static double speed_note_count(MemorySegment struct) {
        return struct.get(speed_note_count$LAYOUT, speed_note_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double speed_note_count
     * }
     */
    public static void speed_note_count(MemorySegment struct, double fieldValue) {
        struct.set(speed_note_count$LAYOUT, speed_note_count$OFFSET, fieldValue);
    }

    private static final OfDouble aim_difficult_strain_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("aim_difficult_strain_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double aim_difficult_strain_count
     * }
     */
    public static final OfDouble aim_difficult_strain_count$layout() {
        return aim_difficult_strain_count$LAYOUT;
    }

    private static final long aim_difficult_strain_count$OFFSET = $LAYOUT.byteOffset(groupElement("aim_difficult_strain_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double aim_difficult_strain_count
     * }
     */
    public static final long aim_difficult_strain_count$offset() {
        return aim_difficult_strain_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double aim_difficult_strain_count
     * }
     */
    public static double aim_difficult_strain_count(MemorySegment struct) {
        return struct.get(aim_difficult_strain_count$LAYOUT, aim_difficult_strain_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double aim_difficult_strain_count
     * }
     */
    public static void aim_difficult_strain_count(MemorySegment struct, double fieldValue) {
        struct.set(aim_difficult_strain_count$LAYOUT, aim_difficult_strain_count$OFFSET, fieldValue);
    }

    private static final OfDouble speed_difficult_strain_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("speed_difficult_strain_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double speed_difficult_strain_count
     * }
     */
    public static final OfDouble speed_difficult_strain_count$layout() {
        return speed_difficult_strain_count$LAYOUT;
    }

    private static final long speed_difficult_strain_count$OFFSET = $LAYOUT.byteOffset(groupElement("speed_difficult_strain_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double speed_difficult_strain_count
     * }
     */
    public static final long speed_difficult_strain_count$offset() {
        return speed_difficult_strain_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double speed_difficult_strain_count
     * }
     */
    public static double speed_difficult_strain_count(MemorySegment struct) {
        return struct.get(speed_difficult_strain_count$LAYOUT, speed_difficult_strain_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double speed_difficult_strain_count
     * }
     */
    public static void speed_difficult_strain_count(MemorySegment struct, double fieldValue) {
        struct.set(speed_difficult_strain_count$LAYOUT, speed_difficult_strain_count$OFFSET, fieldValue);
    }

    private static final OfDouble reading_difficult_note_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("reading_difficult_note_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double reading_difficult_note_count
     * }
     */
    public static final OfDouble reading_difficult_note_count$layout() {
        return reading_difficult_note_count$LAYOUT;
    }

    private static final long reading_difficult_note_count$OFFSET = $LAYOUT.byteOffset(groupElement("reading_difficult_note_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double reading_difficult_note_count
     * }
     */
    public static final long reading_difficult_note_count$offset() {
        return reading_difficult_note_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double reading_difficult_note_count
     * }
     */
    public static double reading_difficult_note_count(MemorySegment struct) {
        return struct.get(reading_difficult_note_count$LAYOUT, reading_difficult_note_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double reading_difficult_note_count
     * }
     */
    public static void reading_difficult_note_count(MemorySegment struct, double fieldValue) {
        struct.set(reading_difficult_note_count$LAYOUT, reading_difficult_note_count$OFFSET, fieldValue);
    }

    private static final OfDouble nested_score_per_object$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("nested_score_per_object"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double nested_score_per_object
     * }
     */
    public static final OfDouble nested_score_per_object$layout() {
        return nested_score_per_object$LAYOUT;
    }

    private static final long nested_score_per_object$OFFSET = $LAYOUT.byteOffset(groupElement("nested_score_per_object"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double nested_score_per_object
     * }
     */
    public static final long nested_score_per_object$offset() {
        return nested_score_per_object$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double nested_score_per_object
     * }
     */
    public static double nested_score_per_object(MemorySegment struct) {
        return struct.get(nested_score_per_object$LAYOUT, nested_score_per_object$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double nested_score_per_object
     * }
     */
    public static void nested_score_per_object(MemorySegment struct, double fieldValue) {
        struct.set(nested_score_per_object$LAYOUT, nested_score_per_object$OFFSET, fieldValue);
    }

    private static final OfDouble legacy_score_base_multiplier$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("legacy_score_base_multiplier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double legacy_score_base_multiplier
     * }
     */
    public static final OfDouble legacy_score_base_multiplier$layout() {
        return legacy_score_base_multiplier$LAYOUT;
    }

    private static final long legacy_score_base_multiplier$OFFSET = $LAYOUT.byteOffset(groupElement("legacy_score_base_multiplier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double legacy_score_base_multiplier
     * }
     */
    public static final long legacy_score_base_multiplier$offset() {
        return legacy_score_base_multiplier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double legacy_score_base_multiplier
     * }
     */
    public static double legacy_score_base_multiplier(MemorySegment struct) {
        return struct.get(legacy_score_base_multiplier$LAYOUT, legacy_score_base_multiplier$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double legacy_score_base_multiplier
     * }
     */
    public static void legacy_score_base_multiplier(MemorySegment struct, double fieldValue) {
        struct.set(legacy_score_base_multiplier$LAYOUT, legacy_score_base_multiplier$OFFSET, fieldValue);
    }

    private static final OfDouble maximum_legacy_combo_score$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("maximum_legacy_combo_score"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double maximum_legacy_combo_score
     * }
     */
    public static final OfDouble maximum_legacy_combo_score$layout() {
        return maximum_legacy_combo_score$LAYOUT;
    }

    private static final long maximum_legacy_combo_score$OFFSET = $LAYOUT.byteOffset(groupElement("maximum_legacy_combo_score"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double maximum_legacy_combo_score
     * }
     */
    public static final long maximum_legacy_combo_score$offset() {
        return maximum_legacy_combo_score$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double maximum_legacy_combo_score
     * }
     */
    public static double maximum_legacy_combo_score(MemorySegment struct) {
        return struct.get(maximum_legacy_combo_score$LAYOUT, maximum_legacy_combo_score$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double maximum_legacy_combo_score
     * }
     */
    public static void maximum_legacy_combo_score(MemorySegment struct, double fieldValue) {
        struct.set(maximum_legacy_combo_score$LAYOUT, maximum_legacy_combo_score$OFFSET, fieldValue);
    }

    private static final OfDouble ar$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ar"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static final OfDouble ar$layout() {
        return ar$LAYOUT;
    }

    private static final long ar$OFFSET = $LAYOUT.byteOffset(groupElement("ar"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static final long ar$offset() {
        return ar$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static double ar(MemorySegment struct) {
        return struct.get(ar$LAYOUT, ar$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ar
     * }
     */
    public static void ar(MemorySegment struct, double fieldValue) {
        struct.set(ar$LAYOUT, ar$OFFSET, fieldValue);
    }

    private static final OfDouble great_hit_window$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("great_hit_window"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static final OfDouble great_hit_window$layout() {
        return great_hit_window$LAYOUT;
    }

    private static final long great_hit_window$OFFSET = $LAYOUT.byteOffset(groupElement("great_hit_window"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static final long great_hit_window$offset() {
        return great_hit_window$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static double great_hit_window(MemorySegment struct) {
        return struct.get(great_hit_window$LAYOUT, great_hit_window$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static void great_hit_window(MemorySegment struct, double fieldValue) {
        struct.set(great_hit_window$LAYOUT, great_hit_window$OFFSET, fieldValue);
    }

    private static final OfDouble ok_hit_window$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ok_hit_window"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static final OfDouble ok_hit_window$layout() {
        return ok_hit_window$LAYOUT;
    }

    private static final long ok_hit_window$OFFSET = $LAYOUT.byteOffset(groupElement("ok_hit_window"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static final long ok_hit_window$offset() {
        return ok_hit_window$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static double ok_hit_window(MemorySegment struct) {
        return struct.get(ok_hit_window$LAYOUT, ok_hit_window$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static void ok_hit_window(MemorySegment struct, double fieldValue) {
        struct.set(ok_hit_window$LAYOUT, ok_hit_window$OFFSET, fieldValue);
    }

    private static final OfDouble meh_hit_window$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("meh_hit_window"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double meh_hit_window
     * }
     */
    public static final OfDouble meh_hit_window$layout() {
        return meh_hit_window$LAYOUT;
    }

    private static final long meh_hit_window$OFFSET = $LAYOUT.byteOffset(groupElement("meh_hit_window"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double meh_hit_window
     * }
     */
    public static final long meh_hit_window$offset() {
        return meh_hit_window$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double meh_hit_window
     * }
     */
    public static double meh_hit_window(MemorySegment struct) {
        return struct.get(meh_hit_window$LAYOUT, meh_hit_window$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double meh_hit_window
     * }
     */
    public static void meh_hit_window(MemorySegment struct, double fieldValue) {
        struct.set(meh_hit_window$LAYOUT, meh_hit_window$OFFSET, fieldValue);
    }

    private static final OfDouble hp$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("hp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double hp
     * }
     */
    public static final OfDouble hp$layout() {
        return hp$LAYOUT;
    }

    private static final long hp$OFFSET = $LAYOUT.byteOffset(groupElement("hp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double hp
     * }
     */
    public static final long hp$offset() {
        return hp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double hp
     * }
     */
    public static double hp(MemorySegment struct) {
        return struct.get(hp$LAYOUT, hp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double hp
     * }
     */
    public static void hp(MemorySegment struct, double fieldValue) {
        struct.set(hp$LAYOUT, hp$OFFSET, fieldValue);
    }

    private static final OfInt n_circles$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_circles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_circles
     * }
     */
    public static final OfInt n_circles$layout() {
        return n_circles$LAYOUT;
    }

    private static final long n_circles$OFFSET = $LAYOUT.byteOffset(groupElement("n_circles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_circles
     * }
     */
    public static final long n_circles$offset() {
        return n_circles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_circles
     * }
     */
    public static int n_circles(MemorySegment struct) {
        return struct.get(n_circles$LAYOUT, n_circles$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_circles
     * }
     */
    public static void n_circles(MemorySegment struct, int fieldValue) {
        struct.set(n_circles$LAYOUT, n_circles$OFFSET, fieldValue);
    }

    private static final OfInt n_sliders$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_sliders"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_sliders
     * }
     */
    public static final OfInt n_sliders$layout() {
        return n_sliders$LAYOUT;
    }

    private static final long n_sliders$OFFSET = $LAYOUT.byteOffset(groupElement("n_sliders"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_sliders
     * }
     */
    public static final long n_sliders$offset() {
        return n_sliders$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_sliders
     * }
     */
    public static int n_sliders(MemorySegment struct) {
        return struct.get(n_sliders$LAYOUT, n_sliders$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_sliders
     * }
     */
    public static void n_sliders(MemorySegment struct, int fieldValue) {
        struct.set(n_sliders$LAYOUT, n_sliders$OFFSET, fieldValue);
    }

    private static final OfInt n_large_ticks$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_large_ticks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_large_ticks
     * }
     */
    public static final OfInt n_large_ticks$layout() {
        return n_large_ticks$LAYOUT;
    }

    private static final long n_large_ticks$OFFSET = $LAYOUT.byteOffset(groupElement("n_large_ticks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_large_ticks
     * }
     */
    public static final long n_large_ticks$offset() {
        return n_large_ticks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_large_ticks
     * }
     */
    public static int n_large_ticks(MemorySegment struct) {
        return struct.get(n_large_ticks$LAYOUT, n_large_ticks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_large_ticks
     * }
     */
    public static void n_large_ticks(MemorySegment struct, int fieldValue) {
        struct.set(n_large_ticks$LAYOUT, n_large_ticks$OFFSET, fieldValue);
    }

    private static final OfInt n_spinners$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_spinners"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_spinners
     * }
     */
    public static final OfInt n_spinners$layout() {
        return n_spinners$LAYOUT;
    }

    private static final long n_spinners$OFFSET = $LAYOUT.byteOffset(groupElement("n_spinners"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_spinners
     * }
     */
    public static final long n_spinners$offset() {
        return n_spinners$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_spinners
     * }
     */
    public static int n_spinners(MemorySegment struct) {
        return struct.get(n_spinners$LAYOUT, n_spinners$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_spinners
     * }
     */
    public static void n_spinners(MemorySegment struct, int fieldValue) {
        struct.set(n_spinners$LAYOUT, n_spinners$OFFSET, fieldValue);
    }

    private static final OfDouble stars$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final OfDouble stars$layout() {
        return stars$LAYOUT;
    }

    private static final long stars$OFFSET = $LAYOUT.byteOffset(groupElement("stars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final long stars$offset() {
        return stars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static double stars(MemorySegment struct) {
        return struct.get(stars$LAYOUT, stars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static void stars(MemorySegment struct, double fieldValue) {
        struct.set(stars$LAYOUT, stars$OFFSET, fieldValue);
    }

    private static final OfInt max_combo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_combo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final OfInt max_combo$layout() {
        return max_combo$LAYOUT;
    }

    private static final long max_combo$OFFSET = $LAYOUT.byteOffset(groupElement("max_combo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final long max_combo$offset() {
        return max_combo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static int max_combo(MemorySegment struct) {
        return struct.get(max_combo$LAYOUT, max_combo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static void max_combo(MemorySegment struct, int fieldValue) {
        struct.set(max_combo$LAYOUT, max_combo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

