// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OsuPerformanceAttributes {
 *     OsuDifficultyAttributes difficulty;
 *     double pp;
 *     double pp_acc;
 *     double pp_aim;
 *     double pp_flashlight;
 *     double pp_reading;
 *     double pp_speed;
 *     double effective_miss_count;
 *     Option_f64 speed_deviation;
 *     double combo_based_estimated_miss_count;
 *     Option_f64 score_based_estimated_miss_count;
 *     double aim_estimated_slider_breaks;
 *     double speed_estimated_slider_breaks;
 * }
 * }
 */
public class OsuPerformanceAttributes {

    OsuPerformanceAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        OsuDifficultyAttributes.layout().withName("difficulty"),
        RosuNative.C_DOUBLE.withName("pp"),
        RosuNative.C_DOUBLE.withName("pp_acc"),
        RosuNative.C_DOUBLE.withName("pp_aim"),
        RosuNative.C_DOUBLE.withName("pp_flashlight"),
        RosuNative.C_DOUBLE.withName("pp_reading"),
        RosuNative.C_DOUBLE.withName("pp_speed"),
        RosuNative.C_DOUBLE.withName("effective_miss_count"),
        Option_f64.layout().withName("speed_deviation"),
        RosuNative.C_DOUBLE.withName("combo_based_estimated_miss_count"),
        Option_f64.layout().withName("score_based_estimated_miss_count"),
        RosuNative.C_DOUBLE.withName("aim_estimated_slider_breaks"),
        RosuNative.C_DOUBLE.withName("speed_estimated_slider_breaks")
    ).withName("OsuPerformanceAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout difficulty$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("difficulty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OsuDifficultyAttributes difficulty
     * }
     */
    public static final GroupLayout difficulty$layout() {
        return difficulty$LAYOUT;
    }

    private static final long difficulty$OFFSET = $LAYOUT.byteOffset(groupElement("difficulty"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OsuDifficultyAttributes difficulty
     * }
     */
    public static final long difficulty$offset() {
        return difficulty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OsuDifficultyAttributes difficulty
     * }
     */
    public static MemorySegment difficulty(MemorySegment struct) {
        return struct.asSlice(difficulty$OFFSET, difficulty$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OsuDifficultyAttributes difficulty
     * }
     */
    public static void difficulty(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, difficulty$OFFSET, difficulty$LAYOUT.byteSize());
    }

    private static final OfDouble pp$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static final OfDouble pp$layout() {
        return pp$LAYOUT;
    }

    private static final long pp$OFFSET = $LAYOUT.byteOffset(groupElement("pp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static final long pp$offset() {
        return pp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static double pp(MemorySegment struct) {
        return struct.get(pp$LAYOUT, pp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp
     * }
     */
    public static void pp(MemorySegment struct, double fieldValue) {
        struct.set(pp$LAYOUT, pp$OFFSET, fieldValue);
    }

    private static final OfDouble pp_acc$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_acc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_acc
     * }
     */
    public static final OfDouble pp_acc$layout() {
        return pp_acc$LAYOUT;
    }

    private static final long pp_acc$OFFSET = $LAYOUT.byteOffset(groupElement("pp_acc"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_acc
     * }
     */
    public static final long pp_acc$offset() {
        return pp_acc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_acc
     * }
     */
    public static double pp_acc(MemorySegment struct) {
        return struct.get(pp_acc$LAYOUT, pp_acc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_acc
     * }
     */
    public static void pp_acc(MemorySegment struct, double fieldValue) {
        struct.set(pp_acc$LAYOUT, pp_acc$OFFSET, fieldValue);
    }

    private static final OfDouble pp_aim$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_aim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_aim
     * }
     */
    public static final OfDouble pp_aim$layout() {
        return pp_aim$LAYOUT;
    }

    private static final long pp_aim$OFFSET = $LAYOUT.byteOffset(groupElement("pp_aim"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_aim
     * }
     */
    public static final long pp_aim$offset() {
        return pp_aim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_aim
     * }
     */
    public static double pp_aim(MemorySegment struct) {
        return struct.get(pp_aim$LAYOUT, pp_aim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_aim
     * }
     */
    public static void pp_aim(MemorySegment struct, double fieldValue) {
        struct.set(pp_aim$LAYOUT, pp_aim$OFFSET, fieldValue);
    }

    private static final OfDouble pp_flashlight$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_flashlight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_flashlight
     * }
     */
    public static final OfDouble pp_flashlight$layout() {
        return pp_flashlight$LAYOUT;
    }

    private static final long pp_flashlight$OFFSET = $LAYOUT.byteOffset(groupElement("pp_flashlight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_flashlight
     * }
     */
    public static final long pp_flashlight$offset() {
        return pp_flashlight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_flashlight
     * }
     */
    public static double pp_flashlight(MemorySegment struct) {
        return struct.get(pp_flashlight$LAYOUT, pp_flashlight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_flashlight
     * }
     */
    public static void pp_flashlight(MemorySegment struct, double fieldValue) {
        struct.set(pp_flashlight$LAYOUT, pp_flashlight$OFFSET, fieldValue);
    }

    private static final OfDouble pp_reading$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_reading"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_reading
     * }
     */
    public static final OfDouble pp_reading$layout() {
        return pp_reading$LAYOUT;
    }

    private static final long pp_reading$OFFSET = $LAYOUT.byteOffset(groupElement("pp_reading"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_reading
     * }
     */
    public static final long pp_reading$offset() {
        return pp_reading$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_reading
     * }
     */
    public static double pp_reading(MemorySegment struct) {
        return struct.get(pp_reading$LAYOUT, pp_reading$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_reading
     * }
     */
    public static void pp_reading(MemorySegment struct, double fieldValue) {
        struct.set(pp_reading$LAYOUT, pp_reading$OFFSET, fieldValue);
    }

    private static final OfDouble pp_speed$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("pp_speed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double pp_speed
     * }
     */
    public static final OfDouble pp_speed$layout() {
        return pp_speed$LAYOUT;
    }

    private static final long pp_speed$OFFSET = $LAYOUT.byteOffset(groupElement("pp_speed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double pp_speed
     * }
     */
    public static final long pp_speed$offset() {
        return pp_speed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double pp_speed
     * }
     */
    public static double pp_speed(MemorySegment struct) {
        return struct.get(pp_speed$LAYOUT, pp_speed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double pp_speed
     * }
     */
    public static void pp_speed(MemorySegment struct, double fieldValue) {
        struct.set(pp_speed$LAYOUT, pp_speed$OFFSET, fieldValue);
    }

    private static final OfDouble effective_miss_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("effective_miss_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double effective_miss_count
     * }
     */
    public static final OfDouble effective_miss_count$layout() {
        return effective_miss_count$LAYOUT;
    }

    private static final long effective_miss_count$OFFSET = $LAYOUT.byteOffset(groupElement("effective_miss_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double effective_miss_count
     * }
     */
    public static final long effective_miss_count$offset() {
        return effective_miss_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double effective_miss_count
     * }
     */
    public static double effective_miss_count(MemorySegment struct) {
        return struct.get(effective_miss_count$LAYOUT, effective_miss_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double effective_miss_count
     * }
     */
    public static void effective_miss_count(MemorySegment struct, double fieldValue) {
        struct.set(effective_miss_count$LAYOUT, effective_miss_count$OFFSET, fieldValue);
    }

    private static final GroupLayout speed_deviation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("speed_deviation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 speed_deviation
     * }
     */
    public static final GroupLayout speed_deviation$layout() {
        return speed_deviation$LAYOUT;
    }

    private static final long speed_deviation$OFFSET = $LAYOUT.byteOffset(groupElement("speed_deviation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 speed_deviation
     * }
     */
    public static final long speed_deviation$offset() {
        return speed_deviation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 speed_deviation
     * }
     */
    public static MemorySegment speed_deviation(MemorySegment struct) {
        return struct.asSlice(speed_deviation$OFFSET, speed_deviation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 speed_deviation
     * }
     */
    public static void speed_deviation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, speed_deviation$OFFSET, speed_deviation$LAYOUT.byteSize());
    }

    private static final OfDouble combo_based_estimated_miss_count$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("combo_based_estimated_miss_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double combo_based_estimated_miss_count
     * }
     */
    public static final OfDouble combo_based_estimated_miss_count$layout() {
        return combo_based_estimated_miss_count$LAYOUT;
    }

    private static final long combo_based_estimated_miss_count$OFFSET = $LAYOUT.byteOffset(groupElement("combo_based_estimated_miss_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double combo_based_estimated_miss_count
     * }
     */
    public static final long combo_based_estimated_miss_count$offset() {
        return combo_based_estimated_miss_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double combo_based_estimated_miss_count
     * }
     */
    public static double combo_based_estimated_miss_count(MemorySegment struct) {
        return struct.get(combo_based_estimated_miss_count$LAYOUT, combo_based_estimated_miss_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double combo_based_estimated_miss_count
     * }
     */
    public static void combo_based_estimated_miss_count(MemorySegment struct, double fieldValue) {
        struct.set(combo_based_estimated_miss_count$LAYOUT, combo_based_estimated_miss_count$OFFSET, fieldValue);
    }

    private static final GroupLayout score_based_estimated_miss_count$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("score_based_estimated_miss_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_f64 score_based_estimated_miss_count
     * }
     */
    public static final GroupLayout score_based_estimated_miss_count$layout() {
        return score_based_estimated_miss_count$LAYOUT;
    }

    private static final long score_based_estimated_miss_count$OFFSET = $LAYOUT.byteOffset(groupElement("score_based_estimated_miss_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_f64 score_based_estimated_miss_count
     * }
     */
    public static final long score_based_estimated_miss_count$offset() {
        return score_based_estimated_miss_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_f64 score_based_estimated_miss_count
     * }
     */
    public static MemorySegment score_based_estimated_miss_count(MemorySegment struct) {
        return struct.asSlice(score_based_estimated_miss_count$OFFSET, score_based_estimated_miss_count$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_f64 score_based_estimated_miss_count
     * }
     */
    public static void score_based_estimated_miss_count(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, score_based_estimated_miss_count$OFFSET, score_based_estimated_miss_count$LAYOUT.byteSize());
    }

    private static final OfDouble aim_estimated_slider_breaks$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("aim_estimated_slider_breaks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double aim_estimated_slider_breaks
     * }
     */
    public static final OfDouble aim_estimated_slider_breaks$layout() {
        return aim_estimated_slider_breaks$LAYOUT;
    }

    private static final long aim_estimated_slider_breaks$OFFSET = $LAYOUT.byteOffset(groupElement("aim_estimated_slider_breaks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double aim_estimated_slider_breaks
     * }
     */
    public static final long aim_estimated_slider_breaks$offset() {
        return aim_estimated_slider_breaks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double aim_estimated_slider_breaks
     * }
     */
    public static double aim_estimated_slider_breaks(MemorySegment struct) {
        return struct.get(aim_estimated_slider_breaks$LAYOUT, aim_estimated_slider_breaks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double aim_estimated_slider_breaks
     * }
     */
    public static void aim_estimated_slider_breaks(MemorySegment struct, double fieldValue) {
        struct.set(aim_estimated_slider_breaks$LAYOUT, aim_estimated_slider_breaks$OFFSET, fieldValue);
    }

    private static final OfDouble speed_estimated_slider_breaks$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("speed_estimated_slider_breaks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double speed_estimated_slider_breaks
     * }
     */
    public static final OfDouble speed_estimated_slider_breaks$layout() {
        return speed_estimated_slider_breaks$LAYOUT;
    }

    private static final long speed_estimated_slider_breaks$OFFSET = $LAYOUT.byteOffset(groupElement("speed_estimated_slider_breaks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double speed_estimated_slider_breaks
     * }
     */
    public static final long speed_estimated_slider_breaks$offset() {
        return speed_estimated_slider_breaks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double speed_estimated_slider_breaks
     * }
     */
    public static double speed_estimated_slider_breaks(MemorySegment struct) {
        return struct.get(speed_estimated_slider_breaks$LAYOUT, speed_estimated_slider_breaks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double speed_estimated_slider_breaks
     * }
     */
    public static void speed_estimated_slider_breaks(MemorySegment struct, double fieldValue) {
        struct.set(speed_estimated_slider_breaks$LAYOUT, speed_estimated_slider_breaks$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

