// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PerformanceAttributes {
 *     uint32_t variant;
 *     union {
 *         OsuPerformanceAttributes osu;
 *         TaikoPerformanceAttributes taiko;
 *         CatchPerformanceAttributes catch_;
 *         ManiaPerformanceAttributes mania;
 *     } payload;
 * }
 * }
 */
public class PerformanceAttributes {

    PerformanceAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("variant"),
        MemoryLayout.paddingLayout(4),
        PerformanceAttributes.payload.layout().withName("payload")
    ).withName("PerformanceAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt variant$LAYOUT = (OfInt)$LAYOUT.select(groupElement("variant"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final OfInt variant$layout() {
        return variant$LAYOUT;
    }

    private static final long variant$OFFSET = $LAYOUT.byteOffset(groupElement("variant"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final long variant$offset() {
        return variant$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static int variant(MemorySegment struct) {
        return struct.get(variant$LAYOUT, variant$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static void variant(MemorySegment struct, int fieldValue) {
        struct.set(variant$LAYOUT, variant$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     OsuPerformanceAttributes osu;
     *     TaikoPerformanceAttributes taiko;
     *     CatchPerformanceAttributes catch_;
     *     ManiaPerformanceAttributes mania;
     * }
     * }
     */
    public static class payload {

        payload() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            OsuPerformanceAttributes.layout().withName("osu"),
            TaikoPerformanceAttributes.layout().withName("taiko"),
            CatchPerformanceAttributes.layout().withName("catch_"),
            ManiaPerformanceAttributes.layout().withName("mania")
        ).withName("$anon$266:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final GroupLayout osu$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("osu"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * OsuPerformanceAttributes osu
         * }
         */
        public static final GroupLayout osu$layout() {
            return osu$LAYOUT;
        }

        private static final long osu$OFFSET = $LAYOUT.byteOffset(groupElement("osu"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * OsuPerformanceAttributes osu
         * }
         */
        public static final long osu$offset() {
            return osu$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * OsuPerformanceAttributes osu
         * }
         */
        public static MemorySegment osu(MemorySegment union) {
            return union.asSlice(osu$OFFSET, osu$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * OsuPerformanceAttributes osu
         * }
         */
        public static void osu(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, osu$OFFSET, osu$LAYOUT.byteSize());
        }

        private static final GroupLayout taiko$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("taiko"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * TaikoPerformanceAttributes taiko
         * }
         */
        public static final GroupLayout taiko$layout() {
            return taiko$LAYOUT;
        }

        private static final long taiko$OFFSET = $LAYOUT.byteOffset(groupElement("taiko"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * TaikoPerformanceAttributes taiko
         * }
         */
        public static final long taiko$offset() {
            return taiko$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * TaikoPerformanceAttributes taiko
         * }
         */
        public static MemorySegment taiko(MemorySegment union) {
            return union.asSlice(taiko$OFFSET, taiko$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * TaikoPerformanceAttributes taiko
         * }
         */
        public static void taiko(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, taiko$OFFSET, taiko$LAYOUT.byteSize());
        }

        private static final GroupLayout catch_$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("catch_"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * CatchPerformanceAttributes catch_
         * }
         */
        public static final GroupLayout catch_$layout() {
            return catch_$LAYOUT;
        }

        private static final long catch_$OFFSET = $LAYOUT.byteOffset(groupElement("catch_"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * CatchPerformanceAttributes catch_
         * }
         */
        public static final long catch_$offset() {
            return catch_$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * CatchPerformanceAttributes catch_
         * }
         */
        public static MemorySegment catch_(MemorySegment union) {
            return union.asSlice(catch_$OFFSET, catch_$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * CatchPerformanceAttributes catch_
         * }
         */
        public static void catch_(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, catch_$OFFSET, catch_$LAYOUT.byteSize());
        }

        private static final GroupLayout mania$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("mania"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * ManiaPerformanceAttributes mania
         * }
         */
        public static final GroupLayout mania$layout() {
            return mania$LAYOUT;
        }

        private static final long mania$OFFSET = $LAYOUT.byteOffset(groupElement("mania"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * ManiaPerformanceAttributes mania
         * }
         */
        public static final long mania$offset() {
            return mania$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * ManiaPerformanceAttributes mania
         * }
         */
        public static MemorySegment mania(MemorySegment union) {
            return union.asSlice(mania$OFFSET, mania$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * ManiaPerformanceAttributes mania
         * }
         */
        public static void mania(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, mania$OFFSET, mania$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout payload$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("payload"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     OsuPerformanceAttributes osu;
     *     TaikoPerformanceAttributes taiko;
     *     CatchPerformanceAttributes catch_;
     *     ManiaPerformanceAttributes mania;
     * } payload
     * }
     */
    public static final GroupLayout payload$layout() {
        return payload$LAYOUT;
    }

    private static final long payload$OFFSET = $LAYOUT.byteOffset(groupElement("payload"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     OsuPerformanceAttributes osu;
     *     TaikoPerformanceAttributes taiko;
     *     CatchPerformanceAttributes catch_;
     *     ManiaPerformanceAttributes mania;
     * } payload
     * }
     */
    public static final long payload$offset() {
        return payload$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     OsuPerformanceAttributes osu;
     *     TaikoPerformanceAttributes taiko;
     *     CatchPerformanceAttributes catch_;
     *     ManiaPerformanceAttributes mania;
     * } payload
     * }
     */
    public static MemorySegment payload(MemorySegment struct) {
        return struct.asSlice(payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     OsuPerformanceAttributes osu;
     *     TaikoPerformanceAttributes taiko;
     *     CatchPerformanceAttributes catch_;
     *     ManiaPerformanceAttributes mania;
     * } payload
     * }
     */
    public static void payload(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

