// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ResultPtrFFIError {
 *     uint32_t variant;
 *     union {
 *         void *ok;
 *         uint32_t err;
 *     } payload;
 * }
 * }
 */
public class ResultPtrFFIError {

    ResultPtrFFIError() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("variant"),
        MemoryLayout.paddingLayout(4),
        ResultPtrFFIError.payload.layout().withName("payload")
    ).withName("ResultPtrFFIError");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt variant$LAYOUT = (OfInt)$LAYOUT.select(groupElement("variant"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final OfInt variant$layout() {
        return variant$LAYOUT;
    }

    private static final long variant$OFFSET = $LAYOUT.byteOffset(groupElement("variant"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static final long variant$offset() {
        return variant$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static int variant(MemorySegment struct) {
        return struct.get(variant$LAYOUT, variant$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t variant
     * }
     */
    public static void variant(MemorySegment struct, int fieldValue) {
        struct.set(variant$LAYOUT, variant$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     void *ok;
     *     uint32_t err;
     * }
     * }
     */
    public static class payload {

        payload() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            RosuNative.C_POINTER.withName("ok"),
            RosuNative.C_INT.withName("err")
        ).withName("$anon$63:46");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final AddressLayout ok$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ok"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * void *ok
         * }
         */
        public static final AddressLayout ok$layout() {
            return ok$LAYOUT;
        }

        private static final long ok$OFFSET = $LAYOUT.byteOffset(groupElement("ok"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * void *ok
         * }
         */
        public static final long ok$offset() {
            return ok$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * void *ok
         * }
         */
        public static MemorySegment ok(MemorySegment union) {
            return union.get(ok$LAYOUT, ok$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * void *ok
         * }
         */
        public static void ok(MemorySegment union, MemorySegment fieldValue) {
            union.set(ok$LAYOUT, ok$OFFSET, fieldValue);
        }

        private static final OfInt err$LAYOUT = (OfInt)$LAYOUT.select(groupElement("err"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * uint32_t err
         * }
         */
        public static final OfInt err$layout() {
            return err$LAYOUT;
        }

        private static final long err$OFFSET = $LAYOUT.byteOffset(groupElement("err"));

        /**
         * Offset for field:
         * {@snippet lang=c :
         * uint32_t err
         * }
         */
        public static final long err$offset() {
            return err$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * uint32_t err
         * }
         */
        public static int err(MemorySegment union) {
            return union.get(err$LAYOUT, err$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * uint32_t err
         * }
         */
        public static void err(MemorySegment union, int fieldValue) {
            union.set(err$LAYOUT, err$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout payload$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("payload"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     void *ok;
     *     uint32_t err;
     * } payload
     * }
     */
    public static final GroupLayout payload$layout() {
        return payload$LAYOUT;
    }

    private static final long payload$OFFSET = $LAYOUT.byteOffset(groupElement("payload"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     void *ok;
     *     uint32_t err;
     * } payload
     * }
     */
    public static final long payload$offset() {
        return payload$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     void *ok;
     *     uint32_t err;
     * } payload
     * }
     */
    public static MemorySegment payload(MemorySegment struct) {
        return struct.asSlice(payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     void *ok;
     *     uint32_t err;
     * } payload
     * }
     */
    public static void payload(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, payload$OFFSET, payload$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

