// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ScoreState {
 *     uint32_t max_combo;
 *     uint32_t osu_large_tick_hits;
 *     uint32_t osu_small_tick_hits;
 *     uint32_t slider_end_hits;
 *     uint32_t n_geki;
 *     uint32_t n_katu;
 *     uint32_t n300;
 *     uint32_t n100;
 *     uint32_t n50;
 *     uint32_t misses;
 *     Option_u32 legacy_total_score;
 * }
 * }
 */
public class ScoreState {

    ScoreState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("max_combo"),
        RosuNative.C_INT.withName("osu_large_tick_hits"),
        RosuNative.C_INT.withName("osu_small_tick_hits"),
        RosuNative.C_INT.withName("slider_end_hits"),
        RosuNative.C_INT.withName("n_geki"),
        RosuNative.C_INT.withName("n_katu"),
        RosuNative.C_INT.withName("n300"),
        RosuNative.C_INT.withName("n100"),
        RosuNative.C_INT.withName("n50"),
        RosuNative.C_INT.withName("misses"),
        Option_u32.layout().withName("legacy_total_score")
    ).withName("ScoreState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt max_combo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_combo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final OfInt max_combo$layout() {
        return max_combo$LAYOUT;
    }

    private static final long max_combo$OFFSET = $LAYOUT.byteOffset(groupElement("max_combo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final long max_combo$offset() {
        return max_combo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static int max_combo(MemorySegment struct) {
        return struct.get(max_combo$LAYOUT, max_combo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static void max_combo(MemorySegment struct, int fieldValue) {
        struct.set(max_combo$LAYOUT, max_combo$OFFSET, fieldValue);
    }

    private static final OfInt osu_large_tick_hits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("osu_large_tick_hits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t osu_large_tick_hits
     * }
     */
    public static final OfInt osu_large_tick_hits$layout() {
        return osu_large_tick_hits$LAYOUT;
    }

    private static final long osu_large_tick_hits$OFFSET = $LAYOUT.byteOffset(groupElement("osu_large_tick_hits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t osu_large_tick_hits
     * }
     */
    public static final long osu_large_tick_hits$offset() {
        return osu_large_tick_hits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t osu_large_tick_hits
     * }
     */
    public static int osu_large_tick_hits(MemorySegment struct) {
        return struct.get(osu_large_tick_hits$LAYOUT, osu_large_tick_hits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t osu_large_tick_hits
     * }
     */
    public static void osu_large_tick_hits(MemorySegment struct, int fieldValue) {
        struct.set(osu_large_tick_hits$LAYOUT, osu_large_tick_hits$OFFSET, fieldValue);
    }

    private static final OfInt osu_small_tick_hits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("osu_small_tick_hits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t osu_small_tick_hits
     * }
     */
    public static final OfInt osu_small_tick_hits$layout() {
        return osu_small_tick_hits$LAYOUT;
    }

    private static final long osu_small_tick_hits$OFFSET = $LAYOUT.byteOffset(groupElement("osu_small_tick_hits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t osu_small_tick_hits
     * }
     */
    public static final long osu_small_tick_hits$offset() {
        return osu_small_tick_hits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t osu_small_tick_hits
     * }
     */
    public static int osu_small_tick_hits(MemorySegment struct) {
        return struct.get(osu_small_tick_hits$LAYOUT, osu_small_tick_hits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t osu_small_tick_hits
     * }
     */
    public static void osu_small_tick_hits(MemorySegment struct, int fieldValue) {
        struct.set(osu_small_tick_hits$LAYOUT, osu_small_tick_hits$OFFSET, fieldValue);
    }

    private static final OfInt slider_end_hits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("slider_end_hits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t slider_end_hits
     * }
     */
    public static final OfInt slider_end_hits$layout() {
        return slider_end_hits$LAYOUT;
    }

    private static final long slider_end_hits$OFFSET = $LAYOUT.byteOffset(groupElement("slider_end_hits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t slider_end_hits
     * }
     */
    public static final long slider_end_hits$offset() {
        return slider_end_hits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t slider_end_hits
     * }
     */
    public static int slider_end_hits(MemorySegment struct) {
        return struct.get(slider_end_hits$LAYOUT, slider_end_hits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t slider_end_hits
     * }
     */
    public static void slider_end_hits(MemorySegment struct, int fieldValue) {
        struct.set(slider_end_hits$LAYOUT, slider_end_hits$OFFSET, fieldValue);
    }

    private static final OfInt n_geki$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_geki"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_geki
     * }
     */
    public static final OfInt n_geki$layout() {
        return n_geki$LAYOUT;
    }

    private static final long n_geki$OFFSET = $LAYOUT.byteOffset(groupElement("n_geki"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_geki
     * }
     */
    public static final long n_geki$offset() {
        return n_geki$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_geki
     * }
     */
    public static int n_geki(MemorySegment struct) {
        return struct.get(n_geki$LAYOUT, n_geki$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_geki
     * }
     */
    public static void n_geki(MemorySegment struct, int fieldValue) {
        struct.set(n_geki$LAYOUT, n_geki$OFFSET, fieldValue);
    }

    private static final OfInt n_katu$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_katu"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_katu
     * }
     */
    public static final OfInt n_katu$layout() {
        return n_katu$LAYOUT;
    }

    private static final long n_katu$OFFSET = $LAYOUT.byteOffset(groupElement("n_katu"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_katu
     * }
     */
    public static final long n_katu$offset() {
        return n_katu$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_katu
     * }
     */
    public static int n_katu(MemorySegment struct) {
        return struct.get(n_katu$LAYOUT, n_katu$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_katu
     * }
     */
    public static void n_katu(MemorySegment struct, int fieldValue) {
        struct.set(n_katu$LAYOUT, n_katu$OFFSET, fieldValue);
    }

    private static final OfInt n300$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n300"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n300
     * }
     */
    public static final OfInt n300$layout() {
        return n300$LAYOUT;
    }

    private static final long n300$OFFSET = $LAYOUT.byteOffset(groupElement("n300"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n300
     * }
     */
    public static final long n300$offset() {
        return n300$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n300
     * }
     */
    public static int n300(MemorySegment struct) {
        return struct.get(n300$LAYOUT, n300$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n300
     * }
     */
    public static void n300(MemorySegment struct, int fieldValue) {
        struct.set(n300$LAYOUT, n300$OFFSET, fieldValue);
    }

    private static final OfInt n100$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n100"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n100
     * }
     */
    public static final OfInt n100$layout() {
        return n100$LAYOUT;
    }

    private static final long n100$OFFSET = $LAYOUT.byteOffset(groupElement("n100"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n100
     * }
     */
    public static final long n100$offset() {
        return n100$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n100
     * }
     */
    public static int n100(MemorySegment struct) {
        return struct.get(n100$LAYOUT, n100$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n100
     * }
     */
    public static void n100(MemorySegment struct, int fieldValue) {
        struct.set(n100$LAYOUT, n100$OFFSET, fieldValue);
    }

    private static final OfInt n50$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n50"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n50
     * }
     */
    public static final OfInt n50$layout() {
        return n50$LAYOUT;
    }

    private static final long n50$OFFSET = $LAYOUT.byteOffset(groupElement("n50"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n50
     * }
     */
    public static final long n50$offset() {
        return n50$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n50
     * }
     */
    public static int n50(MemorySegment struct) {
        return struct.get(n50$LAYOUT, n50$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n50
     * }
     */
    public static void n50(MemorySegment struct, int fieldValue) {
        struct.set(n50$LAYOUT, n50$OFFSET, fieldValue);
    }

    private static final OfInt misses$LAYOUT = (OfInt)$LAYOUT.select(groupElement("misses"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t misses
     * }
     */
    public static final OfInt misses$layout() {
        return misses$LAYOUT;
    }

    private static final long misses$OFFSET = $LAYOUT.byteOffset(groupElement("misses"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t misses
     * }
     */
    public static final long misses$offset() {
        return misses$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t misses
     * }
     */
    public static int misses(MemorySegment struct) {
        return struct.get(misses$LAYOUT, misses$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t misses
     * }
     */
    public static void misses(MemorySegment struct, int fieldValue) {
        struct.set(misses$LAYOUT, misses$OFFSET, fieldValue);
    }

    private static final GroupLayout legacy_total_score$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("legacy_total_score"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Option_u32 legacy_total_score
     * }
     */
    public static final GroupLayout legacy_total_score$layout() {
        return legacy_total_score$LAYOUT;
    }

    private static final long legacy_total_score$OFFSET = $LAYOUT.byteOffset(groupElement("legacy_total_score"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Option_u32 legacy_total_score
     * }
     */
    public static final long legacy_total_score$offset() {
        return legacy_total_score$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Option_u32 legacy_total_score
     * }
     */
    public static MemorySegment legacy_total_score(MemorySegment struct) {
        return struct.asSlice(legacy_total_score$OFFSET, legacy_total_score$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Option_u32 legacy_total_score
     * }
     */
    public static void legacy_total_score(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, legacy_total_score$OFFSET, legacy_total_score$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

