// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SliderData {
 *     uint32_t repeats;
 *     ExpectedDistance expected_dist;
 * }
 * }
 */
public class SliderData {

    SliderData() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_INT.withName("repeats"),
        MemoryLayout.paddingLayout(4),
        ExpectedDistance.layout().withName("expected_dist")
    ).withName("SliderData");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt repeats$LAYOUT = (OfInt)$LAYOUT.select(groupElement("repeats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t repeats
     * }
     */
    public static final OfInt repeats$layout() {
        return repeats$LAYOUT;
    }

    private static final long repeats$OFFSET = $LAYOUT.byteOffset(groupElement("repeats"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t repeats
     * }
     */
    public static final long repeats$offset() {
        return repeats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t repeats
     * }
     */
    public static int repeats(MemorySegment struct) {
        return struct.get(repeats$LAYOUT, repeats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t repeats
     * }
     */
    public static void repeats(MemorySegment struct, int fieldValue) {
        struct.set(repeats$LAYOUT, repeats$OFFSET, fieldValue);
    }

    private static final GroupLayout expected_dist$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("expected_dist"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ExpectedDistance expected_dist
     * }
     */
    public static final GroupLayout expected_dist$layout() {
        return expected_dist$LAYOUT;
    }

    private static final long expected_dist$OFFSET = $LAYOUT.byteOffset(groupElement("expected_dist"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ExpectedDistance expected_dist
     * }
     */
    public static final long expected_dist$offset() {
        return expected_dist$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ExpectedDistance expected_dist
     * }
     */
    public static MemorySegment expected_dist(MemorySegment struct) {
        return struct.asSlice(expected_dist$OFFSET, expected_dist$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ExpectedDistance expected_dist
     * }
     */
    public static void expected_dist(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, expected_dist$OFFSET, expected_dist$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

