// Generated by jextract

package desu.life.raw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TaikoDifficultyAttributes {
 *     double stamina;
 *     double rhythm;
 *     double color;
 *     double reading;
 *     double great_hit_window;
 *     double ok_hit_window;
 *     double mono_stamina_factor;
 *     double mechanical_difficulty;
 *     double consistency_factor;
 *     double stars;
 *     uint32_t max_combo;
 *     bool is_convert;
 * }
 * }
 */
public class TaikoDifficultyAttributes {

    TaikoDifficultyAttributes() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RosuNative.C_DOUBLE.withName("stamina"),
        RosuNative.C_DOUBLE.withName("rhythm"),
        RosuNative.C_DOUBLE.withName("color"),
        RosuNative.C_DOUBLE.withName("reading"),
        RosuNative.C_DOUBLE.withName("great_hit_window"),
        RosuNative.C_DOUBLE.withName("ok_hit_window"),
        RosuNative.C_DOUBLE.withName("mono_stamina_factor"),
        RosuNative.C_DOUBLE.withName("mechanical_difficulty"),
        RosuNative.C_DOUBLE.withName("consistency_factor"),
        RosuNative.C_DOUBLE.withName("stars"),
        RosuNative.C_INT.withName("max_combo"),
        RosuNative.C_BOOL.withName("is_convert"),
        MemoryLayout.paddingLayout(3)
    ).withName("TaikoDifficultyAttributes");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble stamina$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stamina"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stamina
     * }
     */
    public static final OfDouble stamina$layout() {
        return stamina$LAYOUT;
    }

    private static final long stamina$OFFSET = $LAYOUT.byteOffset(groupElement("stamina"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stamina
     * }
     */
    public static final long stamina$offset() {
        return stamina$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stamina
     * }
     */
    public static double stamina(MemorySegment struct) {
        return struct.get(stamina$LAYOUT, stamina$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stamina
     * }
     */
    public static void stamina(MemorySegment struct, double fieldValue) {
        struct.set(stamina$LAYOUT, stamina$OFFSET, fieldValue);
    }

    private static final OfDouble rhythm$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("rhythm"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double rhythm
     * }
     */
    public static final OfDouble rhythm$layout() {
        return rhythm$LAYOUT;
    }

    private static final long rhythm$OFFSET = $LAYOUT.byteOffset(groupElement("rhythm"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double rhythm
     * }
     */
    public static final long rhythm$offset() {
        return rhythm$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double rhythm
     * }
     */
    public static double rhythm(MemorySegment struct) {
        return struct.get(rhythm$LAYOUT, rhythm$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double rhythm
     * }
     */
    public static void rhythm(MemorySegment struct, double fieldValue) {
        struct.set(rhythm$LAYOUT, rhythm$OFFSET, fieldValue);
    }

    private static final OfDouble color$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("color"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double color
     * }
     */
    public static final OfDouble color$layout() {
        return color$LAYOUT;
    }

    private static final long color$OFFSET = $LAYOUT.byteOffset(groupElement("color"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double color
     * }
     */
    public static final long color$offset() {
        return color$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double color
     * }
     */
    public static double color(MemorySegment struct) {
        return struct.get(color$LAYOUT, color$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double color
     * }
     */
    public static void color(MemorySegment struct, double fieldValue) {
        struct.set(color$LAYOUT, color$OFFSET, fieldValue);
    }

    private static final OfDouble reading$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("reading"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static final OfDouble reading$layout() {
        return reading$LAYOUT;
    }

    private static final long reading$OFFSET = $LAYOUT.byteOffset(groupElement("reading"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static final long reading$offset() {
        return reading$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static double reading(MemorySegment struct) {
        return struct.get(reading$LAYOUT, reading$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double reading
     * }
     */
    public static void reading(MemorySegment struct, double fieldValue) {
        struct.set(reading$LAYOUT, reading$OFFSET, fieldValue);
    }

    private static final OfDouble great_hit_window$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("great_hit_window"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static final OfDouble great_hit_window$layout() {
        return great_hit_window$LAYOUT;
    }

    private static final long great_hit_window$OFFSET = $LAYOUT.byteOffset(groupElement("great_hit_window"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static final long great_hit_window$offset() {
        return great_hit_window$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static double great_hit_window(MemorySegment struct) {
        return struct.get(great_hit_window$LAYOUT, great_hit_window$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double great_hit_window
     * }
     */
    public static void great_hit_window(MemorySegment struct, double fieldValue) {
        struct.set(great_hit_window$LAYOUT, great_hit_window$OFFSET, fieldValue);
    }

    private static final OfDouble ok_hit_window$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ok_hit_window"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static final OfDouble ok_hit_window$layout() {
        return ok_hit_window$LAYOUT;
    }

    private static final long ok_hit_window$OFFSET = $LAYOUT.byteOffset(groupElement("ok_hit_window"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static final long ok_hit_window$offset() {
        return ok_hit_window$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static double ok_hit_window(MemorySegment struct) {
        return struct.get(ok_hit_window$LAYOUT, ok_hit_window$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ok_hit_window
     * }
     */
    public static void ok_hit_window(MemorySegment struct, double fieldValue) {
        struct.set(ok_hit_window$LAYOUT, ok_hit_window$OFFSET, fieldValue);
    }

    private static final OfDouble mono_stamina_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mono_stamina_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mono_stamina_factor
     * }
     */
    public static final OfDouble mono_stamina_factor$layout() {
        return mono_stamina_factor$LAYOUT;
    }

    private static final long mono_stamina_factor$OFFSET = $LAYOUT.byteOffset(groupElement("mono_stamina_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mono_stamina_factor
     * }
     */
    public static final long mono_stamina_factor$offset() {
        return mono_stamina_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mono_stamina_factor
     * }
     */
    public static double mono_stamina_factor(MemorySegment struct) {
        return struct.get(mono_stamina_factor$LAYOUT, mono_stamina_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mono_stamina_factor
     * }
     */
    public static void mono_stamina_factor(MemorySegment struct, double fieldValue) {
        struct.set(mono_stamina_factor$LAYOUT, mono_stamina_factor$OFFSET, fieldValue);
    }

    private static final OfDouble mechanical_difficulty$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mechanical_difficulty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mechanical_difficulty
     * }
     */
    public static final OfDouble mechanical_difficulty$layout() {
        return mechanical_difficulty$LAYOUT;
    }

    private static final long mechanical_difficulty$OFFSET = $LAYOUT.byteOffset(groupElement("mechanical_difficulty"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mechanical_difficulty
     * }
     */
    public static final long mechanical_difficulty$offset() {
        return mechanical_difficulty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mechanical_difficulty
     * }
     */
    public static double mechanical_difficulty(MemorySegment struct) {
        return struct.get(mechanical_difficulty$LAYOUT, mechanical_difficulty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mechanical_difficulty
     * }
     */
    public static void mechanical_difficulty(MemorySegment struct, double fieldValue) {
        struct.set(mechanical_difficulty$LAYOUT, mechanical_difficulty$OFFSET, fieldValue);
    }

    private static final OfDouble consistency_factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("consistency_factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double consistency_factor
     * }
     */
    public static final OfDouble consistency_factor$layout() {
        return consistency_factor$LAYOUT;
    }

    private static final long consistency_factor$OFFSET = $LAYOUT.byteOffset(groupElement("consistency_factor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double consistency_factor
     * }
     */
    public static final long consistency_factor$offset() {
        return consistency_factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double consistency_factor
     * }
     */
    public static double consistency_factor(MemorySegment struct) {
        return struct.get(consistency_factor$LAYOUT, consistency_factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double consistency_factor
     * }
     */
    public static void consistency_factor(MemorySegment struct, double fieldValue) {
        struct.set(consistency_factor$LAYOUT, consistency_factor$OFFSET, fieldValue);
    }

    private static final OfDouble stars$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("stars"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final OfDouble stars$layout() {
        return stars$LAYOUT;
    }

    private static final long stars$OFFSET = $LAYOUT.byteOffset(groupElement("stars"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static final long stars$offset() {
        return stars$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static double stars(MemorySegment struct) {
        return struct.get(stars$LAYOUT, stars$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double stars
     * }
     */
    public static void stars(MemorySegment struct, double fieldValue) {
        struct.set(stars$LAYOUT, stars$OFFSET, fieldValue);
    }

    private static final OfInt max_combo$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_combo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final OfInt max_combo$layout() {
        return max_combo$LAYOUT;
    }

    private static final long max_combo$OFFSET = $LAYOUT.byteOffset(groupElement("max_combo"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static final long max_combo$offset() {
        return max_combo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static int max_combo(MemorySegment struct) {
        return struct.get(max_combo$LAYOUT, max_combo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t max_combo
     * }
     */
    public static void max_combo(MemorySegment struct, int fieldValue) {
        struct.set(max_combo$LAYOUT, max_combo$OFFSET, fieldValue);
    }

    private static final OfBoolean is_convert$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_convert"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final OfBoolean is_convert$layout() {
        return is_convert$LAYOUT;
    }

    private static final long is_convert$OFFSET = $LAYOUT.byteOffset(groupElement("is_convert"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static final long is_convert$offset() {
        return is_convert$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static boolean is_convert(MemorySegment struct) {
        return struct.get(is_convert$LAYOUT, is_convert$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_convert
     * }
     */
    public static void is_convert(MemorySegment struct, boolean fieldValue) {
        struct.set(is_convert$LAYOUT, is_convert$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

