<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <CargoPackage>rosu_pp_ffi</CargoPackage>
        <CargoBindingsPackage>rosu_pp_ffi_build</CargoBindingsPackage>
        <CargoWorkspacePath>$(MSBuildThisFileDirectory)/../../</CargoWorkspacePath>
        <NativeRid Condition=" '$(NativeRid)' == '' And '$(RuntimeIdentifier)' != '' ">$(RuntimeIdentifier)</NativeRid>
        <NativeRid Condition=" '$(NativeRid)' == '' ">$(NETCoreSdkPortableRuntimeIdentifier)</NativeRid>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(AotBuild)' == 'true' ">
        <IsAotBuild>true</IsAotBuild>
        <DefineConstants>$(DefineConstants);AOT</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(AotBuild)' != 'true' ">
        <IsAotBuild>false</IsAotBuild>
    </PropertyGroup>

    <!-- Compile-time RIDs -->
    <PropertyGroup Condition=" '$(NativeRid)' == 'win-x64' Or '$(NativeRid)' == 'win-arm64' ">
        <IsWindows>true</IsWindows>
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(NativeRid)' == 'linux-x64' Or '$(NativeRid)' == 'linux-arm64' ">
        <IsLinux>true</IsLinux>
        <IsUnix>true</IsUnix>
        <DefineConstants>$(DefineConstants);LINUX;UNIX</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(NativeRid)' == 'osx-x64' Or '$(NativeRid)' == 'osx-arm64' ">
        <IsMacOS>true</IsMacOS>
        <IsUnix>true</IsUnix>
        <DefineConstants>$(DefineConstants);MACOS;UNIX</DefineConstants>
    </PropertyGroup>

    <!-- Cargo configuration -->
    <PropertyGroup>
        <CargoTargetPath>$(MSBuildThisFileDirectory)/../../target</CargoTargetPath>

        <CargoConfiguration>release</CargoConfiguration>

        <CargoTarget Condition=" '$(NativeRid)' == 'win-x64' ">x86_64-pc-windows-msvc</CargoTarget>
        <CargoTarget Condition=" '$(NativeRid)' == 'win-arm64' ">aarch64-pc-windows-msvc</CargoTarget>
        <CargoTarget Condition=" '$(NativeRid)' == 'linux-x64' ">x86_64-unknown-linux-gnu</CargoTarget>
        <CargoTarget Condition=" '$(NativeRid)' == 'linux-arm64' ">aarch64-unknown-linux-gnu</CargoTarget>
        <CargoTarget Condition=" '$(NativeRid)' == 'osx-x64' ">x86_64-apple-darwin</CargoTarget>
        <CargoTarget Condition=" '$(NativeRid)' == 'osx-arm64' ">aarch64-apple-darwin</CargoTarget>

        <CargoExtension Condition=" '$(IsWindows)' == 'true' ">dll</CargoExtension>
        <CargoExtension Condition=" '$(IsLinux)' == 'true' ">so</CargoExtension>
        <CargoExtension Condition=" '$(IsMacOS)' == 'true' ">dylib</CargoExtension>

        <CargoExtension Condition=" '$(IsWindows)' == 'true' And '$(IsAotBuild)' == 'true' ">lib</CargoExtension>
        <CargoExtension Condition=" '$(IsLinux)' == 'true' And '$(IsAotBuild)' == 'true' ">a</CargoExtension>
        <CargoExtension Condition=" '$(IsMacOS)' == 'true' And '$(IsAotBuild)' == 'true' ">a</CargoExtension>

        <CargoArtifact Condition=" '$(IsWindows)' == 'true' ">$(CargoPackage).$(CargoExtension)</CargoArtifact>
        <CargoArtifact Condition=" '$(IsLinux)' == 'true' ">lib$(CargoPackage).$(CargoExtension)</CargoArtifact>
        <CargoArtifact Condition=" '$(IsMacOS)' == 'true' ">lib$(CargoPackage).$(CargoExtension)</CargoArtifact>

        <CargoArtifactPath>$(CargoTargetPath)/$(CargoTarget)/$(CargoConfiguration)/$(CargoArtifact)</CargoArtifactPath>
    </PropertyGroup>

    <ItemGroup>
        <CargoChannelArg Condition=" '$(CargoChannel)' != '' " Include="+$(CargoChannel)" />
        <CargoBuildArg Include="--target $(CargoTarget)" />
        <CargoBuildArg Condition=" '$(CargoConfiguration)' == 'release' " Include="--release" />
    </ItemGroup>

    <Target Name="Cargo"
            BeforeTargets="BeforeBuild"
            Condition=" '$(UsePrebuiltNativeArtifacts)' != 'true' ">
        <Error Condition=" '$(CargoTarget)' == '' "
               Text="Unsupported native runtime identifier '$(NativeRid)'." />
        <Message Text="Building libs" Importance="high" />
        <Exec Command="cargo @(CargoChannelArg, ' ') build @(CargoBuildArg, ' ') -p $(CargoPackage)" WorkingDirectory="$(CargoWorkspacePath)" />
        <Message Text="Generate Bindings" Importance="high" />
        <Exec Command="cargo @(CargoChannelArg, ' ') build @(CargoBuildArg, ' ') -p $(CargoBindingsPackage)" WorkingDirectory="$(CargoWorkspacePath)" />
    </Target>

    <!-- In AOT builds, add a reference to the IL compiler and link the static native artifact -->
    <ItemGroup Condition=" '$(IsAotBuild)' == 'true' ">
        <!-- This version of the IL Compiler is pinned to the framework (and by extension, ASP.NET) -->
        <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="9.0.0" />

        <IlcArg Include="--completetypemetadata" />
        <IlcArg Include="-g" />
        <NativeLibrary Include="$(CargoArtifactPath)" />
    </ItemGroup>

    <!-- In standard builds, copy the native dynamic artifact to the output dir  -->
    <ItemGroup Condition=" '$(IsAotBuild)' == 'false' And '$(UsePrebuiltNativeArtifacts)' != 'true' ">
        <CargoLibrary Include="$(CargoArtifactPath)" />
    </ItemGroup>

    <Target Name="CargoBuildCopy"
            DependsOnTargets="Cargo"
            BeforeTargets="BeforeBuild"
            Condition=" '$(IsAotBuild)' == 'false' And '$(UsePrebuiltNativeArtifacts)' != 'true' ">
        <Message Text="Copy native libs" Importance="high" />
        <ItemGroup>
			<Content Include="@(CargoLibrary)">
                <Link>runtimes/$(NativeRid)/native/%(Filename)%(Extension)</Link>
                <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            </Content>
            <!-- <EmbeddedResource Include="@(CargoLibrary)" /> -->
		</ItemGroup>
    </Target>
</Project>
